### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by rbellens** [OttomanDeveloper/firebase_admin_sdk#1]
Hi @OttomanDeveloper,

I noticed that you copied my `firebase_admin` package. I appreciate your interest in my work and your intent to build upon it. It is no problem that you make a copy and distribute it. However, it seems that you have removed the original copyright notice and license and replaced it with your own. This is of course not allowed. So, please correct this as soon as possible in both github and pub.dev. 

Additionally, I would advise you to use the fork functionality of github next time. That way it is very clear and transparent what is the origin of the code and what is your contribution to it.

**Comment by OttomanDeveloper** [comment]
Hi Rik! Sorry for this. I was trying to implement admin SDK on my project and I found your package which was not working. so I made changes. 

What do I have to do now? Can you please tell me?

**Comment by rbellens** [comment]
Hi @OttomanDeveloper ,

Thanks for your quick response. You should think of it like writing a paper or something. There as well, you can not simply remove authors or use a text from a different author without proper citation. If you do, it is plagiarism. The more clear it is, what is written by whom, the better, although that is not always feasible.

At least, you should restore the original copyright notice and license. If you made changes to the code and want to add a copyright notice, you can do so in the same LICENSE file, but don't remove the original ones from that file. 

I think, it would also be more clear if you  add some text to the README file that explains that the package is a fork with some reference to the original package.

When that's done, you should push to github and publish a new version to pub.dev, so the latest licenses are available on both platforms.

**Comment by OttomanDeveloper** [comment]
Okay Thanks, I will do that
